#!/usr/bin/env bash
# 04-configure.sh — Configure Wayland flags, copy starter configs
# Run: bash 04-configure.sh   (no sudo needed)

set -euo pipefail

device_icon() {
  local mac="$1"
  if bluetoothctl info "$mac" 2>/dev/null | grep -q "Connected: yes"; then
    printf ''
    return
  fi

  if bluetoothctl info "$mac" 2>/dev/null | grep -q "Paired: yes"; then
    printf '󰂯'
    return
  fi

  printf ''
}

# ── VS Code: force native Wayland via Ozone ──────────────────────────────────
# Applies to: code (Microsoft), code-oss (open source build)

configure_vscode() {
  local flags_file="$HOME/.config/code-flags.conf"
  if [[ -f "$flags_file" ]]; then
    echo "  [skip] $flags_file already exists — not overwriting"
    echo "         Ensure it contains: --ozone-platform=wayland"
  else
    cat > "$flags_file" <<'EOF'
--ozone-platform=wayland
--enable-features=WaylandWindowDecorations
EOF
    echo "  [ok] $flags_file"
  fi

  # code-oss uses a separate flags file
  local oss_flags="$HOME/.config/code-oss-flags.conf"
  if [[ -f "$oss_flags" ]]; then
    echo "  [skip] $oss_flags already exists"
  else
    cp "$HOME/.config/code-flags.conf" "$oss_flags"
    echo "  [ok] $oss_flags"
  fi
}

# ── Chromium: force native Wayland via Ozone ─────────────────────────────────

configure_chromium() {
  local flags_file="$HOME/.config/chromium-flags.conf"
  if [[ -f "$flags_file" ]]; then
    echo "  [skip] $flags_file already exists — not overwriting"
    echo "         Ensure it contains: --ozone-platform=wayland"
  else
    cat > "$flags_file" <<'EOF'
--ozone-platform=wayland
EOF
    echo "  [ok] $flags_file"
  fi
}

# ── Sway starter config ───────────────────────────────────────────────────────

configure_sway() {
  local sway_conf="$HOME/.config/sway/config"
  if [[ -f "$sway_conf" ]]; then
    echo "  [skip] $sway_conf already exists — not overwriting"
  else
    mkdir -p "$HOME/.config/sway"
    cp /etc/sway/config "$sway_conf"
    # Propagate Wayland environment to D-Bus and systemd so Electron apps
    # (VS Code, Chromium) can auto-detect Wayland without extra flags.
    cat >> "$sway_conf" <<'EOF'

# ── Wayland environment propagation ──────────────────────────────────────────
# Required for Electron apps, xdg-desktop-portal, and screen sharing to work.
exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP DISPLAY
EOF
    echo "  [ok] $sway_conf (copied from /etc/sway/config + env propagation added)"
  fi
}

# ── Hyprland starter config ───────────────────────────────────────────────────

configure_hyprland() {
  local hypr_dir="$HOME/.config/hypr"
  mkdir -p "$hypr_dir"
  local main_keyboard_name="at-translated-set-2-keyboard"

  if command -v hyprctl &>/dev/null; then
    local detected_keyboard_name
    detected_keyboard_name=$(hyprctl devices 2>/dev/null | awk '
      /Keyboards:/ { in_keyboards = 1; next }
      /^Mice:/ { in_keyboards = 0 }
      in_keyboards && /^[[:space:]]+[[:alnum:]].*$/ { device = $1; sub(/[[:space:]]+$/, "", device) }
      in_keyboards && /main: yes/ { print device; exit }
    ')
    if [[ -n "$detected_keyboard_name" ]]; then
      main_keyboard_name="$detected_keyboard_name"
    fi
  fi

  local hypr_lua="$hypr_dir/hyprland.lua"
    local refresh_managed_lua="false"
    if [[ -f "$hypr_lua" ]]; then
      if grep -q "Generated by 04-configure.sh" "$hypr_lua" && grep -q "gestures = {" "$hypr_lua"; then
        refresh_managed_lua="true"
        echo "  [info] $hypr_lua is an older managed config — refreshing it"
      else
        echo "  [skip] $hypr_lua already exists — not overwriting"
        return
      fi
    fi

  local source_lua=""
  for candidate in \
    /usr/share/hyprland/hyprland.lua \
    /etc/hypr/hyprland.lua; do
    if [[ -f "$candidate" ]]; then
      source_lua="$candidate"
      break
    fi
  done

  if [[ -n "$source_lua" && "$refresh_managed_lua" != "true" ]]; then
    cp "$source_lua" "$hypr_lua"
    echo "  [ok] $hypr_lua (copied from $source_lua)"
    return
  fi

  cat > "$hypr_lua" <<'EOF'
-- Hyprland Lua starter config
-- Generated by 04-configure.sh for a modern Wayland setup.

local terminal = "kitty"
local fileManager = "kitty yazi"
local menu = "fuzzel"
local mainMod = "SUPER"
local mainKeyboard = "${main_keyboard_name}"

hl.config({
  general = {
    gaps_in = 5,
    gaps_out = 10,
    border_size = 2,
    layout = "dwindle",
  },

  decoration = {
    rounding = 8,
    active_opacity = 1.0,
    inactive_opacity = 1.0,
    shadow = {
      enabled = true,
      range = 8,
      render_power = 3,
      color = "rgba(00000055)",
    },
    blur = {
      enabled = true,
      size = 6,
      passes = 2,
    },
    glow = {
      enabled = true,
      range = 8,
      render_power = 2,
    },
  },

  animations = {
    enabled = true,
  },

  input = {
    kb_layout = "us,ua",
    kb_options = "grp:alt_shift_toggle",
    follow_mouse = 1,
    touchpad = {
      natural_scroll = true,
    },
  },

  misc = {
    vrr = 1,
  },
})

hl.gesture({
  fingers = 3,
  direction = "horizontal",
  action = "workspace",
})

hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("hyprctl dispatch exit"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + Space", hl.dsp.exec_cmd("sh -c 'command -v noctalia >/dev/null 2>&1 && exec noctalia msg panel-toggle launcher || exec " .. menu .. "'"))
hl.bind(mainMod .. " + F", hl.dsp.exec_cmd("hyprctl dispatch fullscreen"))
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd("cliphist list | fuzzel -d | cliphist decode | wl-copy"))

for i = 1, 9 do
  hl.bind(mainMod .. " + " .. tostring(i), hl.dsp.focus({ workspace = i }))
  hl.bind(mainMod .. " + SHIFT + " .. tostring(i), hl.dsp.window.move({ workspace = i }))
end

hl.bind(mainMod .. " + minus", hl.dsp.exec_cmd("hyprctl keyword cursor:zoom_factor 1.0"))
hl.bind(mainMod .. " + equal", hl.dsp.exec_cmd("hyprctl keyword cursor:zoom_factor 1.25"))
hl.bind(mainMod .. " + 0", hl.dsp.exec_cmd("hyprctl keyword cursor:zoom_factor 1.0"))
hl.bind(mainMod .. " + K", hl.dsp.exec_cmd("hyprctl switchxkblayout '" .. mainKeyboard .. "' next"))

-- Laptop multimedia keys: volume, mic, brightness, playback
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true, repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true, repeating = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

hl.window_rule({
  match = { class = "pavucontrol" },
  float = true,
})
hl.window_rule({
  match = { class = "org.gnome.Calculator" },
  float = true,
})
hl.window_rule({
  match = { title = "Picture-in-Picture" },
  float = true,
})

hl.on("hyprland.start", function()
  hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP DISPLAY")
  -- Noctalia has its own bluetooth widget; only run blueman-applet without it.
  hl.exec_cmd("sh -c 'command -v noctalia >/dev/null 2>&1 || exec blueman-applet'")
  hl.exec_cmd(terminal)
  -- Noctalia (if installed) provides the bar + notifications; otherwise fall
  -- back to waybar + mako. Avoids the mako/Noctalia D-Bus name conflict.
  hl.exec_cmd("sh -c 'command -v noctalia >/dev/null 2>&1 || exec waybar'")
  hl.exec_cmd("sh -c 'command -v noctalia >/dev/null 2>&1 && exec noctalia --daemon || exec mako'")
  hl.exec_cmd("hypridle")
  hl.exec_cmd("hyprpaper")
  hl.exec_cmd("hyprsunset")
end)
EOF
  echo "  [ok] $hypr_lua (wrote modern Lua starter config)"
}

# ── Waybar: create config dirs (both WMs share waybar) ───────────────────────

configure_waybar() {
  mkdir -p "$HOME/.config/waybar"
  mkdir -p "$HOME/.config/waybar/scripts"

  if [[ ! -f "$HOME/.config/waybar/scripts/bluetooth-status.sh" ]]; then
    cat > "$HOME/.config/waybar/scripts/bluetooth-status.sh" <<'EOF'
#!/usr/bin/env bash

set -euo pipefail

status() {
  local power_state="off"
  local connected_lines
  local connected_names=()
  local connected_count=0

  if bluetoothctl show 2>/dev/null | grep -q "Powered: yes"; then
    power_state="on"
  fi

  if [[ "$power_state" == "on" ]]; then
    while IFS= read -r line; do
      [[ -z "$line" ]] && continue
      local device_mac device_name
      device_mac="${line#Device }"
      device_mac="${device_mac%% *}"
      device_name="${line#Device $device_mac }"
      connected_names+=("$device_name")
    done < <(bluetoothctl devices Connected 2>/dev/null || true)
    connected_count="${#connected_names[@]}"
  fi

  if [[ "$power_state" == "off" ]]; then
    printf '{"text":"","tooltip":"Bluetooth off","class":"off"}'
    return
  fi

  if [[ "$connected_count" -eq 0 ]]; then
    printf '{"text":"","tooltip":"Bluetooth on | Connected: none","class":"on"}'
    return
  fi

  local tooltip_names
  tooltip_names=$(IFS=', '; printf '%s' "${connected_names[*]}")
  printf '{"text":"%s","tooltip":"Bluetooth on | Connected: %s","class":"connected"}' "$connected_count" "$tooltip_names"
}

pick_device() {
  local prompt="$1"
  local filter_connected="${2:-false}"
  local choices=()
  local selected_mac=""
  local line mac name icon

  while IFS= read -r line; do
    [[ -z "$line" ]] && continue
    mac="${line#Device }"
    mac="${mac%% *}"
    name="${line#Device $mac }"
    icon=$(device_icon "$mac")

    if [[ "$filter_connected" == "true" ]]; then
      if ! bluetoothctl info "$mac" 2>/dev/null | grep -q "Connected: yes"; then
        continue
      fi
    fi

    choices+=("$icon  $name [$mac]")
  done < <(bluetoothctl devices 2>/dev/null || true)

  if [[ ${#choices[@]} -eq 0 ]]; then
    return 1
  fi

  selected_mac=$(printf '%s\n' "${choices[@]}" | fuzzel -d -p "$prompt" | sed -n 's/.*\[\(.*\)\]$/\1/p')
  [[ -n "$selected_mac" ]] || return 1
  printf '%s\n' "$selected_mac"
}

menu() {
  local action
  action=$(printf '%s\n' \
    'Toggle power' \
    'Scan for devices' \
    'Connect paired device' \
    'Disconnect connected device' \
    'Refresh' \
    | fuzzel -d -p 'Bluetooth')

  case "$action" in
    'Toggle power')
      if bluetoothctl show 2>/dev/null | grep -q 'Powered: yes'; then
        bluetoothctl power off >/dev/null 2>&1 || true
      else
        bluetoothctl power on >/dev/null 2>&1 || true
      fi
      ;;
    'Scan for devices')
      bluetoothctl scan on >/dev/null 2>&1 || true
      (sleep 8; bluetoothctl scan off >/dev/null 2>&1 || true) &
      ;;
    'Connect paired device')
      if selected_mac=$(pick_device 'Connect'); then
        bluetoothctl connect "$selected_mac" >/dev/null 2>&1 || true
      fi
      ;;
    'Disconnect connected device')
      if selected_mac=$(pick_device 'Disconnect' true); then
        bluetoothctl disconnect "$selected_mac" >/dev/null 2>&1 || true
      fi
      ;;
    'Refresh'|'')
      ;;
  esac
}

if [[ "${1:-}" == "--menu" ]]; then
  menu
  exit 0
fi

status
EOF
    chmod +x "$HOME/.config/waybar/scripts/bluetooth-status.sh"
    echo "  [ok] ~/.config/waybar/scripts/bluetooth-status.sh"
  fi

  if [[ ! -f "$HOME/.config/waybar/config.jsonc" ]]; then
    cat > "$HOME/.config/waybar/config.jsonc" <<'EOF'
{
  "layer": "top",
  "position": "top",
  "spacing": 10,
  "margin-top": 6,
  "margin-left": 8,
  "margin-right": 8,
  "modules-left": ["custom/bluetooth", "hyprland/language"],
  "modules-center": ["clock"],
   "modules-right": ["pulseaudio", "battery", "tray"],
  "custom/bluetooth": {
    "exec": "/home/zakharchukd/.config/waybar/scripts/bluetooth-status.sh",
    "return-type": "json",
    "interval": 5,
    "signal": 8,
    "on-click": "/home/zakharchukd/.config/waybar/scripts/bluetooth-status.sh --menu",
    "on-click-right": "bluetoothctl power toggle",
    "tooltip": true
  },
  "hyprland/language": {
    "format": "{short}",
    "format-us": "EN",
    "format-ua": "UA",
    "keyboard-name": "${main_keyboard_name}",
    "on-click": "hyprctl switchxkblayout '${main_keyboard_name}' next",
    "tooltip": true,
    "tooltip-format": "{long}"
  },
  "clock": {
    "format": "{:%H:%M}",
    "tooltip-format": "{:%A, %d %B %Y}"
  },
   "pulseaudio": {
     "format": "{volume}% {icon}",
     "format-muted": "MUTE ",
     "format-icons": {
       "default": ["", "", ""]
     },
     "on-click": "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle",
     "on-click-right": "pavucontrol",
     "scroll-step": 5,
     "tooltip": true
   },
  "battery": {
    "states": {
      "warning": 30,
      "critical": 15
    },
    "format": "{capacity}% {icon}",
    "format-charging": "{capacity}% ⚡",
    "format-plugged": "{capacity}% ⚡",
    "format-full": "{capacity}% ✓",
    "format-icons": ["", "", "", "", ""],
    "tooltip": true,
    "tooltip-format": "{timeTo} | {capacity}%"
  },
  "tray": {
    "spacing": 10
  }
}
EOF
    echo "  [ok] ~/.config/waybar/config.jsonc (created Bluetooth-aware bar)"
  else
    echo "  [skip] ~/.config/waybar/config.jsonc already exists"
  fi
}

# ── Mako: create config dir ───────────────────────────────────────────────────

configure_mako() {
  mkdir -p "$HOME/.config/mako"
  if [[ ! -f "$HOME/.config/mako/config" ]]; then
    cat > "$HOME/.config/mako/config" <<'EOF'
# Mako notification daemon config
# See: man 5 mako

font=monospace 11
background-color=#2e3440
text-color=#eceff4
border-color=#5e81ac
border-radius=6
default-timeout=5000
max-visible=5
sort=-time
EOF
    echo "  [ok] ~/.config/mako/config"
  else
    echo "  [skip] ~/.config/mako/config already exists"
  fi
}

# ── Run all ───────────────────────────────────────────────────────────────────

echo "==> Configuring VS Code for native Wayland..."
configure_vscode

echo "==> Configuring Chromium for native Wayland..."
configure_chromium

echo "==> Setting up Sway config..."
configure_sway

echo "==> Setting up Hyprland config..."
configure_hyprland

echo "==> Setting up Waybar config..."
configure_waybar

echo "==> Setting up Mako config..."
configure_mako

echo ""
echo "==> Configuration complete."
echo "    Next: run 05-verify.sh"
