#!/usr/bin/env bash
# 04-configure.sh — Configure Wayland flags, copy starter configs
# Run: bash 04-configure.sh   (no sudo needed)

set -euo pipefail

# ── VS Code: force native Wayland via Ozone ──────────────────────────────────
# Applies to: code (Microsoft), code-oss (open source build)

configure_vscode() {
  local flags_file="$HOME/.config/code-flags.conf"
  if [[ -f "$flags_file" ]]; then
    echo "  [skip] $flags_file already exists — not overwriting"
    echo "         Ensure it contains: --ozone-platform=wayland"
  else
    cat > "$flags_file" <<'EOF'
--ozone-platform=wayland
--enable-features=WaylandWindowDecorations
EOF
    echo "  [ok] $flags_file"
  fi

  # code-oss uses a separate flags file
  local oss_flags="$HOME/.config/code-oss-flags.conf"
  if [[ -f "$oss_flags" ]]; then
    echo "  [skip] $oss_flags already exists"
  else
    cp "$HOME/.config/code-flags.conf" "$oss_flags"
    echo "  [ok] $oss_flags"
  fi
}

# ── Chromium: force native Wayland via Ozone ─────────────────────────────────

configure_chromium() {
  local flags_file="$HOME/.config/chromium-flags.conf"
  if [[ -f "$flags_file" ]]; then
    echo "  [skip] $flags_file already exists — not overwriting"
    echo "         Ensure it contains: --ozone-platform=wayland"
  else
    cat > "$flags_file" <<'EOF'
--ozone-platform=wayland
EOF
    echo "  [ok] $flags_file"
  fi
}

# ── Sway starter config ───────────────────────────────────────────────────────

configure_sway() {
  local sway_conf="$HOME/.config/sway/config"
  if [[ -f "$sway_conf" ]]; then
    echo "  [skip] $sway_conf already exists — not overwriting"
  else
    mkdir -p "$HOME/.config/sway"
    cp /etc/sway/config "$sway_conf"
    # Propagate Wayland environment to D-Bus and systemd so Electron apps
    # (VS Code, Chromium) can auto-detect Wayland without extra flags.
    cat >> "$sway_conf" <<'EOF'

# ── Wayland environment propagation ──────────────────────────────────────────
# Required for Electron apps, xdg-desktop-portal, and screen sharing to work.
exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP DISPLAY
EOF
    echo "  [ok] $sway_conf (copied from /etc/sway/config + env propagation added)"
  fi
}

# ── Hyprland starter config ───────────────────────────────────────────────────

configure_hyprland() {
  local hypr_dir="$HOME/.config/hypr"
  mkdir -p "$hypr_dir"

  local hypr_lua="$hypr_dir/hyprland.lua"
    local refresh_managed_lua="false"
    if [[ -f "$hypr_lua" ]]; then
      if grep -q "Generated by 04-configure.sh" "$hypr_lua" && grep -q "gestures = {" "$hypr_lua"; then
        refresh_managed_lua="true"
        echo "  [info] $hypr_lua is an older managed config — refreshing it"
      else
        echo "  [skip] $hypr_lua already exists — not overwriting"
        return
      fi
    fi

  local source_lua=""
  for candidate in \
    /usr/share/hyprland/hyprland.lua \
    /etc/hypr/hyprland.lua; do
    if [[ -f "$candidate" ]]; then
      source_lua="$candidate"
      break
    fi
  done

  if [[ -n "$source_lua" && "$refresh_managed_lua" != "true" ]]; then
    cp "$source_lua" "$hypr_lua"
    echo "  [ok] $hypr_lua (copied from $source_lua)"
    return
  fi

  cat > "$hypr_lua" <<'EOF'
-- Hyprland Lua starter config
-- Generated by 04-configure.sh for a modern Wayland setup.

local terminal = "kitty"
local fileManager = "kitty yazi"
local menu = "fuzzel"
local mainMod = "SUPER"

hl.config({
  general = {
    gaps_in = 5,
    gaps_out = 10,
    border_size = 2,
    layout = "dwindle",
  },

  decoration = {
    rounding = 8,
    active_opacity = 1.0,
    inactive_opacity = 1.0,
    shadow = {
      enabled = true,
      range = 8,
      render_power = 3,
      color = "rgba(00000055)",
    },
    blur = {
      enabled = true,
      size = 6,
      passes = 2,
    },
    glow = {
      enabled = true,
      range = 8,
      render_power = 2,
    },
  },

  animations = {
    enabled = true,
  },

  input = {
    kb_layout = "us",
    follow_mouse = 1,
    touchpad = {
      natural_scroll = true,
    },
  },

  misc = {
    vrr = 1,
  },
})

hl.gesture({
  fingers = 3,
  direction = "horizontal",
  action = "workspace",
})

hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("hyprctl dispatch exit"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + Space", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + F", hl.dsp.exec_cmd("hyprctl dispatch fullscreen"))
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd("cliphist list | fuzzel -d | cliphist decode | wl-copy"))

for i = 1, 9 do
  hl.bind(mainMod .. " + " .. tostring(i), hl.dsp.focus({ workspace = i }))
  hl.bind(mainMod .. " + SHIFT + " .. tostring(i), hl.dsp.window.move({ workspace = i }))
end

hl.bind(mainMod .. " + minus", hl.dsp.exec_cmd("hyprctl keyword cursor:zoom_factor 1.0"))
hl.bind(mainMod .. " + equal", hl.dsp.exec_cmd("hyprctl keyword cursor:zoom_factor 1.25"))
hl.bind(mainMod .. " + 0", hl.dsp.exec_cmd("hyprctl keyword cursor:zoom_factor 1.0"))

hl.window_rule({
  match = { class = "pavucontrol" },
  float = true,
})
hl.window_rule({
  match = { class = "org.gnome.Calculator" },
  float = true,
})
hl.window_rule({
  match = { title = "Picture-in-Picture" },
  float = true,
})

hl.on("hyprland.start", function()
  hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP DISPLAY")
  hl.exec_cmd(terminal)
  hl.exec_cmd("waybar")
  hl.exec_cmd("mako")
  hl.exec_cmd("hypridle")
  hl.exec_cmd("hyprpaper")
  hl.exec_cmd("hyprsunset")
end)
EOF
  echo "  [ok] $hypr_lua (wrote modern Lua starter config)"
}

# ── Waybar: create config dirs (both WMs share waybar) ───────────────────────

configure_waybar() {
  mkdir -p "$HOME/.config/waybar"
  if [[ ! -f "$HOME/.config/waybar/config.jsonc" ]]; then
    # Copy system default if available
    for candidate in \
      /etc/waybar/config \
      /usr/share/waybar/config.jsonc \
      /usr/share/doc/waybar/examples/config; do
      if [[ -f "$candidate" ]]; then
        cp "$candidate" "$HOME/.config/waybar/config.jsonc"
        echo "  [ok] ~/.config/waybar/config.jsonc (copied from $candidate)"
        return
      fi
    done
    echo "  [info] waybar example config not found — waybar will use its built-in defaults"
  else
    echo "  [skip] ~/.config/waybar/config.jsonc already exists"
  fi
}

# ── Mako: create config dir ───────────────────────────────────────────────────

configure_mako() {
  mkdir -p "$HOME/.config/mako"
  if [[ ! -f "$HOME/.config/mako/config" ]]; then
    cat > "$HOME/.config/mako/config" <<'EOF'
# Mako notification daemon config
# See: man 5 mako

font=monospace 11
background-color=#2e3440
text-color=#eceff4
border-color=#5e81ac
border-radius=6
default-timeout=5000
max-visible=5
sort=-time
EOF
    echo "  [ok] ~/.config/mako/config"
  else
    echo "  [skip] ~/.config/mako/config already exists"
  fi
}

# ── Run all ───────────────────────────────────────────────────────────────────

echo "==> Configuring VS Code for native Wayland..."
configure_vscode

echo "==> Configuring Chromium for native Wayland..."
configure_chromium

echo "==> Setting up Sway config..."
configure_sway

echo "==> Setting up Hyprland config..."
configure_hyprland

echo "==> Setting up Waybar config..."
configure_waybar

echo "==> Setting up Mako config..."
configure_mako

echo ""
echo "==> Configuration complete."
echo "    Next: run 05-verify.sh"
